# Generated by Django 4.1 on 2025-04-09 18:29

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("octofit_tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=djongo.models.fields.ObjectIdField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
    ]
