# Generated by Django 4.1 on 2025-04-09 18:31

from django.db import migrations
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("octofit_tracker", "0002_alter_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="members",
        ),
        migrations.AddField(
            model_name="team",
            name="members",
            field=djongo.models.fields.ArrayReferenceField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="octofit_tracker.user",
            ),
        ),
    ]
